### ISSUE TITLE
import issues with ZBX 4.4

### ISSUE THREAD

**Issue by damo2929** [asosso/zbx3-dell-compellent#1]
get import failed with error

Invalid key "scEnclFanStatus[{#SNMPVALUE}][{#SNMPINDEX}]" for item prototype "Status of Fan "{#SNMPVALUE}" in Enclosure {#SNMPINDEX}" on "Template Dell Compellent": incorrect syntax near "[{#SNMPINDEX}]".

is this a version issue or really invalid syntax ?

**Comment by asosso** [comment]
This template is tested for Zabbix 3.4. (check the `zbx3` in the git repo)
